apiVersion: v1
kind: PersistentVolume
metadata:
  name: order-postgres-volume
  labels:
    type: local
    app: order-postgres
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Delete #remove later
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql/order