apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-postgres-volume-claim
  labels:
    app: order-postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi