apiVersion: v1
kind: PersistentVolume
metadata:
  name: ticket-postgres-volume
  labels:
    type: local
    app: ticket-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql